### PR TITLE
DETECTED: Trojan-DDoS.Shell.Agent.e

### PR DESCRIPTION
**Pull request by NIRVANA101**
https://www.virustotal.com/gui/file/53d613776cbd02191ed2a4675a5f18ab909f11d195564a7055f599f5e99b544f?

I have test the shell process behavior too, it's sending some packets in an unknown server. (Where it should only be sending traffic to the target host)

### CODE REVIEW

**Comment by NIRVANA101** [comment]
@danieldanielecki Malicious code detected, you might want to remove this ASAP.
Documented in 2016 (Same Hashes found):
https://threats.kaspersky.com/en/class/Trojan-DDoS/

**Comment by NIRVANA101** [comment]
Specified Signature:
https://www.clavister.com/advisories/antivirus/984472

**Comment by danieldanielecki** [comment]
People can use it with antivirus set to off, not surprised Kaspersky detects it...

**Comment by NIRVANA101** [comment]
@danieldanielecki Let's add a description (warning) then.

**Comment by NIRVANA101** [comment]
Oh, just saw the description.

**Pull request closed without merging**
